### ISSUE TITLE
[Feature Request] Zombie Player is Invisible When Player Skin Doesn't Exist

### ISSUE THREAD

**Issue by Darkosto** [Corosauce/Zombie_Players#18]
Hey Corosus!

I've been looking at using the Zombie players mod in a bit of a different capacity, I was hoping to use Content Creator Integration to allow my twitch chat to spawn in helpful zombies in my world. There's one small problem I'm having and that is when a player does not have a Minecraft Skin, the Zombie Player is invisible. Is there any way you'd be able to add a fallback skin if this occurs or at least a config option when using it in this unique way? So far, everything else is working fantastically and I'm really enjoying the mod!

I know this is a bit outside of the mod scope but I think it would be a neat feature regardless!

Thank you and have a great rest of your day!
Darkosto

MC: 1.18.2 
Forge: 40.2.0
Zombie Players: 1.3.10
CoroUtil: 1.2.44

**Comment by Corosauce** [comment]
Good catch, fixed 👍 

https://github.com/Corosauce/Zombie_Players/commit/35d6b27a06a56f50ab464d7ddf60ce18cf54cf21
