### ISSUE TITLE
Zombie Players error executing task

### ISSUE THREAD

**Issue by diefesson** [Corosauce/Zombie_Players#2]
this bug crashs the game (just severe lag if VannilaFix is installed)

https://paste.dimdev.org/ujakedoguz.mccrash - uploaded by VannilaFix

it occurs when the mod tries to spawn a zombie player, either naturaly or when player dies

**Comment by Corosauce** [comment]
No idea why that ones happening, I know vanillaFix likes to produce false positive errors, but I'll catch that one myself now, https://github.com/Corosauce/Zombie_Players/commit/c900c124d75dab3506a21c0ca63d6d9ec4de9458
