### ISSUE TITLE
Zombie entities are registered too late

### ISSUE THREAD

**Issue by Pyrofab** [Corosauce/Zombie_Players#3]
The zombie entity is registered during `FMLInitializationEvent` instead of `RegistryEvent.Register<EntityEntry>`. This causes other mods looking through the registry (eg. Dissolution) to not see them and skip any adequate compatibility.

**Comment by Corosauce** [comment]
Fixed, new build coming in a bit https://github.com/Corosauce/Zombie_Players/commit/8a9731e2a2318f53fdf4b8a66a12e8fdb9e9de87
