### ISSUE TITLE
Zombie player and pigman crash the game

### ISSUE THREAD

**Issue by SirAron111** [Corosauce/Zombie_Players#4]
I may have found a bug that crashes the game.
Every time I die near at least 2 zombie pigman and my zombie player spawns they crash the game.
Here is the crash report
https://pastebin.com/XwEvaAjP

**Comment by Corosauce** [comment]
Looks like the still ongoing maaybe reliquary crash https://github.com/P3pp3rF1y/Reliquary/issues/355

Can't quite reproduce in my zombie players / zombie awareness environment. I don't do any targetting overriding stuff so I don't see how it could be my mods at fault.

I might dig into this issue further to see if I can help though, hrmmm.

**Comment by SirAron111** [comment]
I found what’s wrong but i am not a modder able to fix it.
The mod author from corail tombstones helped me locate the bug.
It is a problem with forge itself that causes mobs that have a revenge function to mess up. It was something in forge 2777 and up I think. But these versions and up are needed to run many other mods so many Modpack makers can’t downgrade. Here https://github.com/Corail31/tombstone_lite/issues/42

**Comment by Corosauce** [comment]
Thanks for the info, I'll keep my talks in those threads then, going to see if we could maybe fix this in forge itself.
