### ISSUE TITLE
Zombie player AI causing the game (corosus.zombie_players.entity.ai.EntityAIAvoidEntityOnLowHealth)

### ISSUE THREAD

**Issue by SirAron111** [Corosauce/Zombie_Players#5]
Zombie player AI crashing the game (corosus.zombie_players.entity.ai.EntityAIAvoidEntityOnLowHealth)
https://pastebin.com/AHFJ4ekH here is the log

**Comment by coolsimulations** [comment]
Also having Zombie Player AI crashing the game from this issue.
[crash-2019-03-11_17.16.11-server.txt](https://github.com/Corosauce/Zombie_Players/files/2954361/crash-2019-03-11_17.16.11-server.txt)

**Comment by Corosauce** [comment]
Whoops, should be fixed, new build going out now.
